#!/bin/bash

# Check and install dependencies
install_dependencies() {
    if !command -v zenity &>/dev/null; then
        echo -e "\e[33mInstalling required dependencies...\e[0m"
        sudo apt install zenity -y >/dev/null 2>&1
        echo -e "\e[32mDependencies Installed!\e[0m"
    fi
}
install_dependencies

chmod +x script/*

clear
echo -e "\e[K"
echo -e "\e[H"
echo -e "\t\t\t\e[1m\e[33m---------------------Minever Debug Console---------------------\e[0m\e[0m"

log_dir="$PWD/script.log"
main_menu() {
    exec > >(tee -i "$log_dir") 2>&1
    choice=$(zenity --list --title="Menu" --text="<span size='xx-large'><b>Minever</b></span>" --column="Choice" --width=400 --height=250 \
        "Start" \
        "Stop" \
        "⚙️ Options" \
        "Exit")
    if [ $? -ne 0 ]; then
        # User canceled or closed the dialog
        echo -e "\e[33mExited Setup.\e[0m"
        exit
    fi
    # Handle the selected choice
    case "$choice" in
    "Start")
        # Add your START logic here
        echo "Selected: START"
        cd script
        ./start
        ;;
    "Stop")
        # Add your STOP logic here
        echo "Selected: STOP"
        . script/control
        stop
        ;;
    "⚙️ Options")
        # Display additional options menu
        options_menu
        ;;
    "Exit")
        # Handle exit
        echo "Selected: Exit"
        exit 0
        ;;
    *)
        echo "Invalid choice"
        exit 0
        ;;
    esac
}

options_menu() {
    exec > >(tee -i "$log_dir") 2>&1
    choice=$(zenity --list --title="Minever: Setup Menu" --text="<b>Select an action:</b>" --column="Choice" --width=800 --height=400 \
        "Install Server" \
        "Server Configuration" \
        "Install Ngrok" \
        "Afk/Bpytop" \
        "Clear Server Logs" \
        "Exit Setup")

    if [ $? -ne 0 ]; then
        # User canceled or closed the dialog
        echo -e "\e[33mExited Setup.\e[0m"
        exit
    fi

    case "$choice" in
    
    "Install Server")
        . script/control
        install
        ;;

    "Server Configuration")
        ./script/config
        ;;
    "Install Ngrok")
        . script/tools
        ngrok
        ;;
    "Afk/Bpytop")
        . script/tools
        bpytop
        ;;
    "Clear Server Logs")
        . script/tools
        clear_logs
        ;;
    "Exit")
        echo "Exited Setup."
        exit 0
        ;;
    *)
        echo "Invalid choice."
        exit 0
        ;;
    esac
}

main_menu